### ISSUE TITLE
Feature-Application Tracker

### ISSUE THREAD

**Issue by alangan17** [alangan17/jobhunter#5]
- [ ] Save Application Date, Time, Source (e.g. Direct application in company, Linkedin easy apply)
- [ ] Save Application Stage (e.g. 1st interview)
- [ ] Save Interview keywords, video ref, thank you letter
